---
- name: uwsgi - Install uwsgi
  apt: pkg={{ item }} state=installed
  with_items:
    - uwsgi
    - uwsgi-plugin-python
  tags:
    - packages

#- name: Nginx - Add configuration odoo.conf
#  template:
#    src: "templates/{{ item }}.j2"
#    dest: "{{nginx.etc_path}}/sites-available/odoo"
#    owner: "root"
#    group: "root"
#    mode: 0755
#  with_items:
#    - nginx_odoo

