---
- name: uwsgi - Install uwsgi
  apt: pkg={{ item }} state=installed
  with_items:
    - uwsgi
    - uwsgi-plugin-python
  tags:
    - packages

- name: Odoo - Change openerp-wsgi.py
  template:
    src: "templates/{{ item }}.j2"
    dest: "/home/{{ system.odoo_user }}/{{ odoo.home }}/openerp-wsgi.py"
    owner: "odoo"
    group: "odoo"
    mode: 0755
  with_items:
    - openerp_wsgi_py

- name: Nginx - Add configuration odoo.conf
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/odoo.ini"
    owner: "odoo"
    group: "odoo"
    mode: 0755
  with_items:
    - odoo_ini

- name: Odoo - Change openerp-wsgi.py
  template:
    src: "templates/{{ item }}.j2"
    dest: "/home/{{ system.odoo_user }}/{{ odoo.home }}/openerp-wsgi.py"
    owner: "odoo"
    group: "odoo"
    mode: 0755
  with_items:
    - openerp_wsgi_py

- name: Restart uwsgi
  service: name=odoo state=restarted
