---

- name: Update system
  apt: update_cache=yes

- name: Install requeriments
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - byobu
    - emacs23-nox
    - python-pip
    - python-dev
    - libpq-dev
    - python-psycopg2
    - libjpeg62-dev 
    - libpng++-dev 
    - python-dev 
    - libxml2-dev 
    - libxslt1-dev 
    - libldap2-dev
    - libsasl2-dev 
    - libssl-dev
  tags:
    - packages

- name: Create Odoo group
  group: name={{ system.odoo_group }} state=present
  tags: ['users','configuration']


- name: Crete Odoo user
  user: name={{ system.odoo_user }} generate_ssh_key=yes ssh_key_bits=2048 state=present
  tags: ['users','configuration']

- name: Create path
  file: path=/home/{{ system.odoo_user }}/{{ odoo.home }} state=directory owner={{ system.odoo_user }} group={{ system.odoo_group }}
 
