---
- name: Install PostgreSQL
  apt: pkg={{ item }} #state=installed
  with_items:
    - postgresql-common
    - postgresql-contrib
    - postgresql-{{ postgresql.version }}
  tags:
    - packages

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db=template1
                   name={{ postgresql.user }}
                   password={{ postgresql.user_password }}
                   priv=ALL
                   state=present

- name: PostgresSQL | Add permission
  sudo_user: postgres
  postgresql_user: name={{ postgresql.user }} role_attr_flags=SUPERUSER,CREATEDB
